name: Build image container, store in ghcr.io

# Only triggering of this branches
on:
  release:
    types:
      - created

jobs:
  package:
    name: Build image container, store in ghcr.io
    runs-on: ubuntu-18.04 # ATTN - if change, needs also updated `.actrc`
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build image with gradle
        run: >
          ./gradlew bootBuildImage
        env:
          repository: ${{ github.repository }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}